openapi: 3.0.1
info:
  title: OpenAPI definition
  version: v0
servers:
  - url: http://localhost:8080
    description: Generated server url
paths:
  /api/produtos/{id}:
    get:
      tags:
        - produto-resource
      operationId: produtoUnico
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Produto'
    put:
      tags:
        - produto-resource
      operationId: atualizaProduto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Produto'
    delete:
      tags:
        - produto-resource
      operationId: deletaProduto
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: integer
            format: int64
      responses:
        '200':
          description: OK
  /api/produtos:
    get:
      tags:
        - produto-resource
      operationId: listaProdutos
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Produto'
    post:
      tags:
        - produto-resource
      operationId: salvaProduto
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Produto'
        required: true
      responses:
        '200':
          description: OK
          content:
            '*/*':
              schema:
                $ref: '#/components/schemas/Produto'
  /api/resetcache:
    get:
      tags:
        - produto-resource
      operationId: resetacache
      responses:
        '200':
          description: OK
components:
  schemas:
    Link:
      type: object
      properties:
        rel:
          type: string
        href:
          type: string
        hreflang:
          type: string
        media:
          type: string
        title:
          type: string
        type:
          type: string
        deprecation:
          type: string
        profile:
          type: string
        name:
          type: string
    Produto:
      type: object
      properties:
        id:
          type: integer
          format: int64
        nome:
          type: string
        quantidade:
          type: number
        valor:
          type: number
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
