swagger: '2.0'
info:
  description: API REST de cadastro de produtos
  version: '1.0'
  title: Produtos API REST
  termsOfService: Termos de serviço
  contact:
    name: Leonardo Eduardo
    url: https://www.linkedin.com/in/leonardo-eduardo-8a20b6221/
    email: leonardo.eduardo@gmail.com
  license:
    name: Apache License Version 2.0
    url: http://www.apache.org/licensen.html
host: localhost:8080
basePath: /
tags:
  - name: produto-resource
    description: Produto Resource
paths:
  /api/produtos:
    get:
      tags:
        - produto-resource
      summary: Retorna uma lista de produtos
      operationId: listaProdutosUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
          schema:
            type: array
            items:
              $ref: '#/definitions/Produto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    post:
      tags:
        - produto-resource
      summary: Salva um produto
      operationId: salvaProdutoUsingPOST
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - in: body
          name: produto
          description: produto
          required: true
          schema:
            $ref: '#/definitions/Produto'
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Produto'
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
  /api/produtos/{id}:
    get:
      tags:
        - produto-resource
      summary: Retorna um único produto
      operationId: produtoUnicoUsingGET
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
          schema:
            $ref: '#/definitions/Produto'
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    put:
      tags:
        - produto-resource
      summary: Atualiza um produto
      operationId: atualizaProdutoUsingPUT
      consumes:
        - application/json
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
        - in: body
          name: produtoatualizado
          description: produtoatualizado
          required: true
          schema:
            $ref: '/definitions/Produto'
      responses:
        '200':
          description: OK
        '201':
          description: Created
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
    delete:
      tags:
        - produto-resource
      summary: Apaga um único produto
      operationId: deletaProdutoUsingDELETE
      produces:
        - '*/*'
      parameters:
        - name: id
          in: path
          description: id
          required: true
          type: integer
          format: int64
      responses:
        '200':
          description: OK
        '204':
          description: No Content
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
      deprecated: false
  /api/resetcache:
    get:
      tags:
        - produto-resource
      summary: resetacache
      operationId: resetacacheUsingGET
      produces:
        - '*/*'
      responses:
        '200':
          description: OK
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '404':
          description: Not Found
      deprecated: false
definitions:
  Produto:
    type: object
    properties:
      id:
        type: integer
        format: int64
     